#!/bin/bash
#
# Copyright 2016 Hewlett Packard Enterprise Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

PBCDIR=/usr/share/python-brickclient
mkdir $PBCDIR

# create the virtual environment
virtualenv $PBCDIR/venv

# Install the required packages inside virtual env
$PBCDIR/venv/bin/pip install python-brick-cinderclient-ext

ln -s $PBCDIR/venv/bin/python-brickclient /usr/local/bin/python-brickclient
