#!/bin/bash
# Copyright 2012 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

source $_LIB/common-defaults
# options for create-baremetal-image.sh

if [ "${DISTRO_NAME}" = "rhel" ] && [ "${DIB_RELEASE}" = "8" ]; then
    # xfs is the default file-system for RHEL8
    export DEFAULT_FS_TYPE=xfs
else
    export DEFAULT_FS_TYPE=ext4
fi

export FS_TYPE=${FS_TYPE:-$DEFAULT_FS_TYPE}
# Used to set the file extension only at this stage.
export IMAGE_TYPE=${IMAGE_TYPE:-qcow2}
export IMAGE_NAME=${IMAGE_NAME:-image}
