#!/bin/bash
# The base image created by kiwi does not contain an initrd so create one
# here.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# To have access to FS_TYPE
_LIB="/tmp/opensuse-extras"
source $_LIB/img-defaults

# This is to tell mkinitrd to include the right tools for the root filesystem
# that will actually be used for the final image. This is likely something
# different than what the chroot is currently on (which might currently be a
# tmpfs even).
echo "rootfstype=$FS_TYPE" > /etc/sysconfig/initrd

# openSuse mkinitrd requires a valid root device be in fstab.
sed -i 's/vda1/sda1/' /etc/fstab
mkinitrd -A -B

# And cleanup again
rm /etc/sysconfig/initrd
