#!/bin/bash
# The base tbz-image created by kiwi does not contain an initrd so create one
# here. 

set -eu

# To have access to FS_TYPE
_LIB="/tmp/opensuse-extras"
source $_LIB/img-defaults

# This is to tell mkinitrd to include the right tools for the root filesystem
# that will actually be used for the final image. This is likely something
# different than what the chroot is currently on (which might currently be a
# tmpfs even).
echo "rootfstype=$FS_TYPE" > /etc/sysconfig/initrd

mkinitrd -A

# And cleanup again
rm /etc/sysconfig/initrd
