#!/bin/bash
set -eux

install-packages python-pip

pip install -U distribute # required by virtualenv
pip install virtualenv

install -m 0755 -o root -g root $(dirname $0)/../bin/os-svc-install /usr/local/bin/os-svc-install
install -m 0755 -o root -g root $(dirname $0)/../bin/os-svc-daemon  /usr/local/bin/os-svc-daemon
install -m 0755 -o root -g root $(dirname $0)/../bin/os-db-create   /usr/local/bin/os-db-create

install -m 0755 -o root -g root -d /opt/stack/venvs
