#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

install-packages -e python-dev git cloud-init
# dnf removes unused dependencies by default. As we installed cloud-init before
# dmidecode, dnf removes dmidecode above as an unused dependency.
# TODO(dtantsur): use `dnf mark` from dnf 1.1.1 in install-packages once this
# command is widely available.
install-packages dmidecode

rm -rf /tmp/ironic-python-agent

case "$DIB_INIT_SYSTEM" in
    upstart)
        if [ -f /etc/init/ufw.conf ]; then
            mv /etc/init/ufw.conf /etc/init/ufw.conf.disabled
        fi
        ;;
    systemd)
        systemctl disable iptables.service
        systemctl enable $(svc-map ironic-python-agent).service
        ;;
    sysv)
        update-rc.d iptables disable
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
