#!/bin/bash

set -eu
set -o pipefail

cat << EOF > /etc/yum.repos.d/centos7-latest.repo
[rhel7]
name=centos7
baseurl=http://buildlogs.centos.org/centos/7/os/x86_64-latest/
enabled=1
metadata_expire=7d
gpgcheck=0
EOF

cat << EOF > /etc/yum.repos.d/epel.repo
[epel]
name=Extra Packages for Enterprise Linux 7 - \$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=\$basearch
failovermethod=priority
enabled=1
gpgcheck=0
EOF
