#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cat << EOF > /etc/yum.repos.d/centos7-latest.repo
[centos7]
name=centos7
mirrorlist=http://mirrorlist.centos.org/?release=7&arch=\$basearch&repo=os&infra=\$infra
enabled=1
metadata_expire=7d
gpgcheck=0
EOF

cat << EOF > /etc/yum.repos.d/epel.repo
[epel]
name=Extra Packages for Enterprise Linux 7 - \$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=\$basearch
failovermethod=priority
enabled=1
gpgcheck=0
EOF
