#!/bin/bash
set -eux

install-packages lvm2
os-svc-install -n cinder -u cinder -r https://github.com/openstack/cinder.git -c cinder-all

os-svc-daemon cinder-api cinder cinder-api "--config-dir /etc/cinder"
os-svc-daemon cinder-volume cinder cinder-volume "--config-dir /etc/cinder"
os-svc-daemon cinder-scheduler cinder cinder-scheduler "--config-dir /etc/cinder"
mkdir -p /etc/tgt/conf.d
echo 'include /etc/tgt/conf.d/cinder_tgt.conf' > /etc/tgt/targets.conf
echo 'include /var/run/cinder/volumes/*' > /etc/tgt/conf.d/cinder_tgt.conf

echo "cinder ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/cinder
chmod 0440 /etc/sudoers.d/cinder
visudo -c
