#!/bin/bash
# Initialize devstack in the bootstrap image

set -e
set -o xtrace

install-packages git
if [ -n "$http_proxy" ]; then
    sudo -Hiu stack git config --global http.proxy $http_proxy
fi
sudo -Hiu stack git clone https://github.com/openstack-dev/devstack.git
