#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        ;;
    systemd)
        systemctl enable init-ibft-interfaces.service
        ;;
    sysv)
        update-rc.d init-ibft-interfaces.init defaults
        ;;
    *)
        echo "Unsupported init system $DIB_INIT_SYSTEM"
        exit 1
        ;;
esac
