#!/bin/bash
#
# Copyright 2019 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Ensure that dbus-broker is enabled; it seems that because of the
# transition between dbus-daemon and dbus-broker (see
# https://pagure.io/fesco/issue/1853) the .spec files could possibly
# not enable this (likely related to ordering or something we do in
# the non-standardish chroot building) and a 2019 system with no dbus
# is very unhappy (networkmanager fails, etc).
if [[ ${DISTRO_NAME} == 'fedora' && ${DIB_RELEASE} -ge 29 ]]; then
    systemctl --no-reload enable dbus-broker.service
fi
