#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

case "$DISTRO_NAME" in
    almalinux* | centos* | rhel* | rocky*)
    dnf install -y elrepo-release.noarch
    if [ ${DIB_ELREPO_KERNEL:-0} -eq 1 ]; then
        rpm -q dnf-plugins-core || dnf install -y dnf-plugins-core
        dnf config-manager --set-enabled "elrepo-kernel"
    fi
    ;;
    *)
    echo "Distro \"$DISTRO_NAME\" is not supported"
    exit 1
    ;;
esac
exit 0
