#!/bin/bash
set -eu
set -o pipefail
set -o xtrace

touch /var/log/first-boot.d.log
chmod 0600 /var/log/first-boot.d.log

/usr/local/bin/dib-run-parts /etc/first-boot.d >> /var/log/first-boot.d.log 2>&1
rm -fr /etc/first-boot.d
# delete itself
rm $0
