#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Set cloud-init to allow password authentication
if [ -n "${DIB_CLOUD_INIT_ALLOW_SSH_PWAUTH:-}" ]; then
    if [ -f "/etc/cloud/cloud.cfg" ]; then
        if [ -z "$(cat /etc/cloud/cloud.cfg | grep ssh_pwauth)" ]; then
            echo "ssh_pwauth not exist. append to EOF"
            sudo sh -c 'echo "ssh_pwauth: 1" >> /etc/cloud/cloud.cfg'
        else
            echo "ssh_pwauth exist. make sure ssh_pwauth enabled"
            sed -i -e 's/ssh_pwauth: *0/ssh_pwauth: 1/g' /etc/cloud/cloud.cfg
            sed -i -e 's/ssh_pwauth: *False/ssh_pwauth: True/g' /etc/cloud/cloud.cfg
            sed -i -e 's/ssh_pwauth: *false/ssh_pwauth: true/g' /etc/cloud/cloud.cfg
        fi
    fi
fi
