#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DISTRO_NAME == "fedora" && $DIB_RELEASE -eq 22 ]]; then
    # we need dnf mark command from dnf 1.1.1, which is pretty recent
    dnf --refresh update -y dnf
fi
