#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Ensure the python3 interpreter and YAML libraries are installed
# early (even before package-installs, which is written in Python and
# uses YAML).

if [[ ${DISTRO_NAME} =~ (centos|rhel) ]]; then
    # Ensure the "user" python3 package is installed
    # so we have /usr/bin/python3 and pyyaml.
    dnf install -y python3 python3-pyyaml
fi
