#!/bin/bash

if [[ ${DIB_DEBUG_TRACE:-0} -gt 0 ]]; then
    set -x
fi
set -eu
set -o pipefail

# make sure system is in a consistent state
echo 'PYTHON_TARGETS="python3_4"' >> /etc/portage/make.conf
eselect python set python3.4
# allow these uninstalls to fail as they may not be installed
set +e
emerge -C -q dev-lang/python:2.7
emerge -C -q dev-vcs/git
set -e
USE="-build" emerge -q --backtrack=99 --jobs=2 --update --newuse --deep --with-bdeps=y @world
# rebuild packages that might need it
USE="-build" emerge -q --jobs=2 --usepkg=n @preserved-rebuild
# remove unneeded packages
USE="-build" emerge --verbose=n --depclean
# rebuild packages that might have somehow depended on the unneeded packages
USE="-build" emerge -q --jobs=2 --usepkg=n @preserved-rebuild

# update config files
etc-update --automode -5

# clean up portage files
emerge --verbose=n --depclean
emaint all -f
eselect news read all

rm -Rf /root/.ccache/* /usr/src/* /var/cache/edb/dep/* /var/cache/genkernel/* /var/empty/* /var/run/* /var/state/* /var/tmp/*
rm -Rf /etc/*- /etc/*.old /etc/ssh/ssh_host_* /root/.*history /root/.lesshst /root/.ssh/known_hosts /root/.viminfo /usr/share/genkernel /usr/lib64/python*/site-packages/gentoolkit/test/eclean/testdistfiles.tar.gz
if [[ "${GENTOO_PORTAGE_CLEANUP}" != "False" ]]; then
    rm -Rf /usr/portage/* /var/cache/portage/distfiles
fi

# shrink a bit
for i in $(find /var/log -type f); do echo > $i; done
find /usr/share/man/ -mindepth 1  -maxdepth 1 -path "/usr/share/man/man*" -prune -o -exec rm -rf {} \;

# make it so we don't have to reinstall grub
if [[ -a /usr/sbin/grub2-install ]]; then
    mkdir -p /tmp/grub
    touch /tmp/grub/install
fi
