#!/bin/bash
# Save the HTTP if one is available.
# XXX: Obviously not suitable for downloadable images.

set -e
set -o xtrace

if [ -n "$http_proxy" ]; then
    if [ -d ~stack ]; then
      echo export no_proxy=192.0.2.1 >> ~stack/.profile
      echo export http_proxy=$http_proxy >> ~stack/.profile
    fi
    echo "Acquire::http::Proxy \"$http_proxy\";" > /etc/apt/apt.conf.d/61-use-http-proxy
fi
