#!/bin/bash
# Save user SSH public key if available.
# XXX: Obviously not suitable for downloadable images.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -e "/tmp/in_target.d/ssh-authorized-keys" ]; then
    mkdir -p /root/.ssh
    cat /tmp/in_target.d/ssh-authorized-keys >> /root/.ssh/authorized_keys
    chmod 0700 /root/.ssh
    chmod 0600 /root/.ssh/authorized_keys
fi
