#!/bin/bash
# Copyright (c) 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

KERNEL_CONF_FILE=/etc/kernel-img.conf

if [ -e  "$KERNEL_CONF_FILE" ]; then
    # Remove the line if already set
    sed -i "/^link_in_boot.*/d" "$KERNEL_CONF_FILE"
fi

# Set the kernel config option
echo "link_in_boot = yes" >>"$KERNEL_CONF_FILE"
