#!/bin/bash
set -eux

install-packages openvswitch-switch
os-svc-install -n quantum -u quantum -r https://github.com/openstack/quantum.git

mkdir -p /var/lib/quantum && chown -R quantum:quantum /var/lib/quantum

os-svc-daemon quantum-openvswitch-agent quantum quantum-openvswitch-agent \
    "--config-file /etc/quantum/quantum.conf  --config-file /etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini --config-dir /etc/quantum"
os-svc-daemon quantum-server quantum quantum-server \
    "--config-file /etc/quantum/quantum.conf  --config-file /etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini --config-dir /etc/quantum"

echo "quantum ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/quantum
chmod 0440 /etc/sudoers.d/quantum
visudo -c
