#!/bin/bash
# Copyright (c) 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

XS_TOOLS_DIR=$(mktemp -d)
mount -o loop /tmp/xs-tools.iso $XS_TOOLS_DIR
pushd $XS_TOOLS_DIR/Linux
case "$DISTRO_NAME" in
    'ubuntu'|'debian')
        # Seriously
        source versions.deb
        dpkg -i $XE_GUEST_UTILITIES_PKG_FILE_amd64
        ;;
    'fedora'|'centos'|'centos7'|'opensuse')
        source versions.rpm
        rpm -Uvh $XE_GUEST_UTILITIES_PKG_FILE_x86_64
        ;;
esac

popd
umount $XS_TOOLS_DIR
