#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

PIP_CACHE_DIR=$DIB_IMAGE_CACHE/pip
mkdir -p $PIP_CACHE_DIR

sudo mkdir -p $TMP_MOUNT_PATH/tmp/pip
sudo mount --bind $PIP_CACHE_DIR $TMP_MOUNT_PATH/tmp/pip
