#!/bin/bash
set -eu

# TODO: make this easily configurable
db_pass=stackdb

service mysql restart

create-os-db keystone keystone $db_pass
keystone-manage db_sync

create-os-db cinder cinder $db_pass
cinder-manage db sync

create-os-db nova nova $db_pass
nova-manage db sync

create-os-db nova_bm nova $db_pass
nova-baremetal-manage db sync

create-os-db glance glance $db_pass
glance-manage db_sync

create-os-db ovs_quantum quantum $db_pass

