#!/bin/sh

set -uex

install-packages \
    python-pip python-psutil

# Boto in Ubuntu 12.10 is too old. Newer boto's aren't
# supported by heat-api-cfn. Bug ref: http://pad.lv/1122472
pip install 'boto==2.5.2' heat-cfntools
cfn-create-aws-symlinks --source /usr/local/bin
