#!/bin/bash

set -eu
set -o pipefail

MIRROR_SOURCE=~/.cache/image-create/pypi/mirror/
if [ -d "$MIRROR_SOURCE" ]; then
    MIRROR_TARGET=$TMP_MOUNT_PATH/tmp/pypi

    sudo mkdir -p $MIRROR_SOURCE $MIRROR_TARGET
    sudo mount --bind $MIRROR_SOURCE $MIRROR_TARGET
fi
