#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

MIRROR_SOURCE=$DIB_IMAGE_CACHE/pypi/mirror/
if [ -d "$MIRROR_SOURCE" ]; then
    MIRROR_TARGET=$TMP_MOUNT_PATH/tmp/pypi

    sudo mkdir -p $MIRROR_SOURCE $MIRROR_TARGET
    sudo mount --bind $MIRROR_SOURCE $MIRROR_TARGET
fi
