#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]
[ -n "$TARGET_ROOT" ]

if [[ "amd64 x86_64" =~ "$ARCH" ]]; then
    ARCH="x86_64"
    DIB_CLOUD_IMAGES=${DIB_CLOUD_IMAGES:-https://download.rockylinux.org/pub/rocky/${DIB_RELEASE}/images}
else
    echo 'centos root element only support the x86_64 for $ARCH'
    exit 1
fi



DIB_LOCAL_IMAGE=${DIB_LOCAL_IMAGE:-}

if [ -n "$DIB_LOCAL_IMAGE" ]; then
    IMAGE_LOCATION=$DIB_LOCAL_IMAGE
    # No need to copy a local image into the cache directory, so just specify
    # the cached path as the original path.
    CACHED_IMAGE=$IMAGE_LOCATION
    BASE_IMAGE_FILE=$(basename $DIB_LOCAL_IMAGE)
    BASE_IMAGE_TAR=$BASE_IMAGE_FILE.tgz
else
    DIB_FLAVOR=${DIB_FLAVOR:-GenericCloud}
    BASE_IMAGE_FILE=${BASE_IMAGE_FILE:-$(curl -s https://download.rockylinux.org/pub/rocky/${DIB_RELEASE}/images/ | grep -o "Rocky-.[^>]*${DIB_FLAVOR}-.[^>]*.qcow2" | sort -r | head -1)}
    BASE_IMAGE_TAR=$BASE_IMAGE_FILE.tgz
    IMAGE_LOCATION=$DIB_CLOUD_IMAGES/$BASE_IMAGE_FILE
    CACHED_IMAGE=$DIB_IMAGE_CACHE/$BASE_IMAGE_FILE
fi

$TMP_HOOKS_PATH/bin/extract-image $BASE_IMAGE_FILE $BASE_IMAGE_TAR $IMAGE_LOCATION $CACHED_IMAGE
