#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Setup ccache symlinks, as openSUSE's ccache package doesn't
# include them.
mkdir -p /usr/lib/ccache
for tool in cc gcc; do
    ln -s /usr/bin/ccache /usr/lib/ccache/$tool
done
