#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$ARCH" ]

if [ 'amd64' = "$ARCH" ] ; then
    ARCH="x86_64"
fi

BASE_URL=http://download.fedoraproject.org/pub/epel
case "$DISTRO_NAME" in
    rhel7|centos7)
        RELEASE=7
        URL=$BASE_URL/$RELEASE/x86_64/e/
        ;;
    rhel)
        RELEASE=6
        URL=$BASE_URL/$RELEASE/$ARCH/
        ;;
    *)
        echo "$DISTRO_NAME is not supported"
        exit 1
        ;;
esac
PKG_NAME=$(wget -q $URL -O - |grep -oE "(href=\"epel-release-$RELEASE-[0-9,.].*)" | cut -d'"' -f2)
rpm -q epel-release || yum install -y $URL/$PKG_NAME
