#!/bin/bash
set -eu
set -o pipefail

if [[ "rhel7 centos7" =~ "$DISTRO_NAME" ]]; then
    rpm -q epel-release || yum install -y http://download.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
elif [[ "rhel" =~ "$DISTRO_NAME" ]]; then
    rpm -q epel-release || yum install -y http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
fi
