#!/bin/bash
# Store the build-time environment and command line arguments

set -e
source $_LIB/die
[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"

echo "$DIB_ENV" > $TMP_HOOKS_PATH/dib_environment
echo "$DIB_ARGS" > $TMP_HOOKS_PATH/dib_arguments
