#!/bin/bash

set -eux
set -o pipefail

if [ "openSUSE project" = "$(lsb_release -is)" ]; then
    # workaround for https://bugzilla.novell.com/show_bug.cgi?id=859493
    rm -f /dev/mapper/loop*_part1
fi
