#!/bin/bash
# Install baseline packages and tools.

set -e

DISTRO=`lsb_release -si`

case $DISTRO in
  'Ubuntu'|'Debian')
    # Note: add-apt-repository would be nice for RPM platforms too - so when we
    # need something like it, create a wrapper in dpkg/bin and fedora/bin.
    apt-get -y update
    install-packages python-software-properties
    add-apt-repository -y ppa:tripleo/demo
    ;;
esac
