#!/bin/bash
# Install baseline packages and tools.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case $DISTRO_NAME in
    'ubuntu'|'debian')
        # Note: add-apt-repository would be nice for RPM platforms too - so when we
        # need something like it, create a wrapper in dpkg/bin and fedora/bin.
        apt-get -y update
        if [ "${DIB_RELEASE}" = "precise" ]; then
            install-packages python-software-properties
        else
            install-packages software-properties-common
        fi
        ;;
esac
