#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ ${DIB_RELEASE} == tumbleweed ]] ; then
    login_defs=/usr/etc/login.defs
else
    login_defs=/etc/login.defs
fi
sed -i -e "s,^USERGROUPS_ENAB.*$,USERGROUPS_ENAB yes," $login_defs
