#!/bin/bash
#
# Copyright 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# It would be eversogreat if we didn't need to do crap like this
echo $DISTRO_NAME > /etc/hostname

# If you want eth0 and eth1 created as DHCP based interfaces, enable
# this.  You don't want this if systemd is going to call the
# interfaces on the real system something else, or if you're using a
# network-manager like cloud-init, glean or systemd-networkd that will
# handle the interfaces dynamically.
if [[ "${DIB_APT_MINIMAL_CREATE_INTERFACES:-1}" -eq "1" ]]; then
    mkdir -p /etc/network/interfaces.d
    if ! grep -E -q '^source(|-directory) /etc/network/interfaces.d/\*' /etc/network/interfaces; then
        echo "source /etc/network/interfaces.d/*" >> /etc/network/interfaces
        echo 'Network configuration set to source /etc/network/interfaces.d/*'
    fi
    for interface in eth0 eth1; do
        cat << EOF | tee /etc/network/interfaces.d/$interface
auto $interface
iface $interface inet dhcp
EOF
    done
fi
