#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

SCRIPTDIR=$(dirname $0)

# Because NetworkManager can't automatically create default connection
# profiles for InfiniBand interfaces, we are installing
# NetworkManager-system-connections-infiniband.nmconnection to
# NetworkManager to create a wildcard InfiniBand connection profile
install -D -g root -o root -m 0600 ${SCRIPTDIR}/NetworkManager-system-connections-infiniband.nmconnection /etc/NetworkManager/system-connections/infiniband.nmconnection
exit 0
