#!/bin/bash
#
# Copyright 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

# Set the below variable to allow hpssacli to be installed from custom URLs.
DIB_HPSSACLI_URL=${DIB_HPSSACLI_URL:-https://ftp.hp.com/pub/softlib2/software1/pubsw-linux/p1857046646/v109216/hpssacli-2.30-6.0.x86_64.rpm}
curl -k -o /tmp/hpssacli.rpm $DIB_HPSSACLI_URL

if [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
    # There is no deb package for hpssacli.  Install with alien.
    alien -i /tmp/hpssacli.rpm
else
    rpm -iv /tmp/hpssacli.rpm
fi

rm -f /tmp/hpssacli.rpm

# Install proliantutils python module in the
# virtual environment of ironic-python-agent.
# This is pre-installed by
# ironic-agent/install.d/ironic-agent-source-install/60-ironic-agent-install.
IPA_VENV=/usr/share/ironic-python-agent/venv
if [[ -d "$IPA_VENV" ]]; then
    $IPA_VENV/bin/pip install proliantutils
else
    pip install proliantutils
fi
