#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

cat << EOF | sudo tee ${TARGET_ROOT}/.extra_settings > /dev/null
DIB_DEBIAN_ALT_INIT_PACKAGE=systemd-sysv
EOF
