#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ $DISTRO_NAME = 'opensuse' ] ; then
    # workaround for https://bugzilla.novell.com/show_bug.cgi?id=859493
    rm -f /dev/mapper/loop*_part1
fi
