#!/bin/bash

set -e

[ -n "$TARGET_ROOT" ]

sudo mv $TARGET_ROOT/sbin/start-stop-daemon.REAL $TARGET_ROOT/sbin/start-stop-daemon

if [ -f $TARGET_ROOT/sbin/initctl.REAL ]
then
    sudo mv $TARGET_ROOT/sbin/initctl.REAL $TARGET_ROOT/sbin/initctl
fi

sudo rm $TARGET_ROOT/usr/sbin/policy-rc.d
