#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TARGET_ROOT" ]

# Undo our proxy support
sudo rm -f $TARGET_ROOT/etc/apt/apt.conf.d/60img-build-proxy
