#!/bin/bash
# Do an apt-get clean. This will free some space.

set -eu
set -o pipefail

if ! chroot ${TARGET_ROOT} mount | grep /var/cache/apt/archives; then
    sudo chroot ${TARGET_ROOT} apt-get clean
fi
