#!/bin/bash

set -e

yum remove -y grub2
# Install grub2 dependencies to minimise packages installed during finalise.
install-packages grub2-tools gettext os-prober system-logos

# Ensure grub2 rpm is in the yum cache
install-packages -d grub2

# Copy grub2 rpm out of mounted yum cache for install during finalise
mkdir /tmp/grub
basearch=$(cat /etc/yum/vars/basearch)
cp $(find /tmp/yum/$basearch -regex ".*/grub2-[0-9].*\.rpm") /tmp/grub
echo "rpm -i /tmp/grub/*.rpm" > /tmp/grub/install

#GRUB_CFG=/boot/grub2/grub.cfg

#[ -f "$GRUB_CFG" ]

# Update the config to have the search UUID of the image being built.
# When partition staging is moved to a separate stage, this will need to happen
# there. This generates a non-UUID config, which is irrelevant for booting with
# hypervisor kernel + ramdisk, and fixed up by 51-grub for vm images.
#GRUB_DISABLE_LINUX_UUID=true grub2-mkconfig -o $GRUB_CFG
