#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "i386" = "$ARCH" ]; then
    basearch=i386
    arch=i686
elif [ "amd64" = "$ARCH" ]; then
    basearch=x86_64
    arch=x86_64
elif [[ "$ARCH" = "ppc64" ]]; then
    basearch=ppc64
    arch=ppc64
elif [[ "$ARCH" = "ppc64el" ]]; then
    basearch=ppc64el
    arch=ppc64el
else
    echo "********************"
    echo "Unknown arch '$ARCH'"
    echo "********************"
    exit 1
fi

echo $basearch > /etc/yum/vars/basearch
echo $arch > /etc/yum/vars/arch
