#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        # nothing to do
        exit 0
        ;;
    systemd)
        if [[ ${DISTRO_NAME} == centos && ${DIB_RELEASE} == 7 ]]; then
            if [[ ${DIB_SIMPLE_INIT_NETWORKMANAGER} != 1 ]]; then
                # NOTE(pabelanger): Glean requires network.service for
                # these platforms when not using networkmanager
                # Not available on Centos 8
                # NOTE(ianw) we should evaluate if Fedora needs this
                systemctl enable network.service
            fi
        elif [[ ${DISTRO_NAME} =~ (opensuse) ]]; then
            # on suse, this is named wicked.service, but it's the same
            # as network.service.
            systemctl enable wicked.service
        else
            # NOTE(ianw): it might be better to whitelist platforms in
            # the future, but for now assume it will "just work"
            continue
        fi
        ;;
    openrc)
        # let dib-init-system's postinstall handle enabling init scripts
        exit 0
        ;;
    sysv)
        # nothing to do
        exit 0
        ;;
    *)
        echo "Unsupported init system $DIB_INIT_SYSTEM"
        exit 1
        ;;
esac
