#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

DIB_DISTRIBUTION_MIRROR=${DIB_DISTRIBUTION_MIRROR:-}

[ -n "$DIB_DISTRIBUTION_MIRROR" ] || exit 0

# Only set the mirror for the Base, Extras and Updates repositories
# The others aren't enabled and do not exist on all mirrors
sed -e "s,^#baseurl=https://download.rockylinux.org/pub/rocky/,baseurl=$DIB_DISTRIBUTION_MIRROR/,;/^mirrorlist=/d" -i /etc/yum.repos.d/Rocky-BaseOS.repo
sed -e "s,^#baseurl=https://download.rockylinux.org/pub/rocky/,baseurl=$DIB_DISTRIBUTION_MIRROR/,;/^mirrorlist=/d" -i /etc/yum.repos.d/Rocky-AppStream.repo
sed -e "s,^#baseurl=https://download.rockylinux.org/pub/rocky/,baseurl=$DIB_DISTRIBUTION_MIRROR/,;/^mirrorlist=/d" -i /etc/yum.repos.d/Rocky-Plus.repo
sed -e "s,^#baseurl=https://download.rockylinux.org/pub/rocky/,baseurl=$DIB_DISTRIBUTION_MIRROR/,;/^mirrorlist=/d" -i /etc/yum.repos.d/Rocky-Extras.repo
sed -e "s,^#baseurl=https://download.rockylinux.org/pub/rocky/,baseurl=$DIB_DISTRIBUTION_MIRROR/,;/^mirrorlist=/d" -i /etc/yum.repos.d/Rocky-PowerTools.repo
