#!/bin/bash
# Install openstack-selinux if it is available
# dib-lint: disable=sete

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -u
set -o pipefail

HAS_PACKAGE=$(yum list | grep openstack-selinux)
if [ -n "$HAS_PACKAGE" ]; then
    install-packages openstack-selinux
fi
