#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

install-packages python-dev qemu-utils parted hdparm util-linux genisoimage gcc

# Install the latest version of pip and setuptools which has some
# fixes for building behind proxy.
curl -o /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
python /tmp/get-pip.py
rm -f /tmp/get-pip.py
pip install -U setuptools

pip install -r /tmp/ironic-python-agent/requirements.txt
pip install /tmp/ironic-python-agent

sudo echo $'[Unit]
Description=Ironic Python Agent\n
[Service]
ExecStart=/usr/bin/ironic-python-agent
Restart=always
RestartSec=30s\n
[Install]
WantedBy=multi-user.target\n' > /usr/lib/systemd/system/ironic-python-agent.service

sudo systemctl enable ironic-python-agent.service
