#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# As this is run in cleanup, it's already been automatically unmounted,
# so all we need to do here is remove the directory
sudo rmdir $TMP_MOUNT_PATH/tmp/ccache || true
