#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Cloud images may hard code the eth0/ens* interfaces so they
# boot with DHCP.

# Fedora
rm -f /etc/sysconfig/network-scripts/ifcfg-eth*
rm -f /etc/sysconfig/network-scripts/ifcfg-en*

# SUSE
rm -f /etc/sysconfig/network/ifcfg-eth*
rm -f /etc/sysconfig/network/ifcfg-en*

# Ubuntu and Debian
rm -f /etc/network/interfaces.d/eth*
rm -f /etc/network/interfaces.d/en*

# Gentoo
rm -f /etc/conf.d/net*

# /etc/network/interfaces distributions
if [ -f "/etc/network/interfaces" ]; then
    printf "auto lo\niface lo inet loopback\n\n" > /etc/network/interfaces
    if [ -d "/etc/network/interfaces.d/" ]; then
        if [ "$DISTRO_NAME" == "ubuntu" ] && [ "$DIB_RELEASE" == "trusty" ]; then
            printf "source-directory interfaces.d\n\n" >> /etc/network/interfaces
        else
            printf "source /etc/network/interfaces.d/*\n\n" >> /etc/network/interfaces
        fi
    fi
fi
