#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        # nothing to do
        exit 0
        ;;
    systemd)
        if [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
            # NOTE(pabelanger): Only support ubuntu / debian today.
            systemctl enable ssh-keygen.service
        else
            # Since we are not enabling it, delete it.
            rm /usr/lib/systemd/system/ssh-keygen.service
        fi
        ;;
    openrc)
        # let dib-init-system's postinstall handle enabling init scripts
        exit 0
        ;;
    sysv)
        # nothing to do
        exit 0
        ;;
    *)
        echo "Unsupported init system $DIB_INIT_SYSTEM"
        exit 1
        ;;
esac
