#!/bin/bash
set -eux
set -o pipefail

dest_dir="$TMP_MOUNT_PATH/usr/share/package-installs/"
sudo mkdir -p $dest_dir

for ELEMENT in $IMAGE_ELEMENT ; do
    for DIR in ${ELEMENTS_PATH//:/ }; do
        if [ -f "$DIR/$ELEMENT/package-installs.yaml" ]; then
            sudo cp $DIR/$ELEMENT/package-installs.yaml $dest_dir/$ELEMENT.yaml
        fi
    done
done
