#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          keylime-agent
# Required-Start:    $local_fs networking
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# X-Start-Before:
# Short-Description: Keylime Agent
# Description:       The keylime-agent is deployed to the node for attestation
### END INIT INFO

NAME=keylime-agent
INIT_NAME=/etc/init.d/${NAME}
SCRIPT_NAME=/usr/local/bin/keylime_agent

[ -x $SCRIPT_NAME ] || exit 0

case "$1" in
    start)
        $SCRIPT_NAME --config-dir /etc/keylime-agent.d/
        ;;
    stop)
        ;;
    *)
        echo "Usage: $INIT_NAME {start|stop}"
        exit 1
        ;;
esac

exit 0
