#!/bin/bash

set -eux
set -o pipefail

if [ -x "$TMP_MOUNT_PATH/tmp/clean_up_qemu_binary" ] ; then
    "$TMP_MOUNT_PATH/tmp/clean_up_qemu_binary"
    rm -rf "$TMP_MOUNT_PATH/tmp/clean_up_qemu_binary"
fi
