#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

python_path=$(command -v python${DIB_PYTHON_VERSION})
if [ -z "$python_path" ]; then
    echo "Could not find python${DIB_PYTHON_VERSION} executable."
    exit 1
fi

ln -sf $python_path /usr/local/bin/dib-python
