#!/bin/bash
#
# Copyright 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# This is not using install-packages because it's before install-packages can
# work - and is work needed to make it possible for it to work
if [ -x $TMP_MOUNT_PATH/usr/bin/apt-get ] ; then
    sudo chroot $TMP_MOUNT_PATH apt-get update
    sudo chroot $TMP_MOUNT_PATH apt-get -y install python
elif [ -x $TMP_MOUNT_PATH/bin/dnf ] ; then
    sudo chroot $TMP_MOUNT_PATH dnf install -y findutils
elif [ -x $TMP_MOUNT_PATH/usr/bin/yum ] ; then
    sudo chroot $TMP_MOUNT_PATH yum install -y findutils
fi
