#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# This is packages that are required for installation by other
# elements (like base) but aren't actually available for this
# platform.  This is a bit of a hack
echo "dkms" > /tmp/yum-blacklist
