#!/bin/bash
set -eux

TEMPLATES=git://github.com/tripleo/openstack-config-templates.git

sudo apt-get install --yes git python-pip
pip install -U git+https://github.com/tripleo/os-config-applier.git

mkdir -p /opt/stack
git clone $TEMPLATES /opt/stack/openstack-config-templates

cat > /etc/init/os-config-applier.conf <<- eof
start on runlevel [2345]
task
exec os-config-applier -t /opt/stack/openstack-config-templates/templates
eof
