#!/bin/bash
set -eux

TEMPLATES=git://github.com/tripleo/openstack-config-templates.git

sudo apt-get install --yes git python-pip
pip install -U git+https://github.com/tripleo/os-config-applier.git

mkdir -p /opt/stack
git clone $TEMPLATES /opt/stack/openstack-config-templates

runscript=$(os-refresh-config --print-base)/configuration.d/10-os-config-applier
mkdir -p $(dirname $runscript)
cat > $runscript <<- eof
#!/bin/sh
exec os-config-applier -t /opt/stack/openstack-config-templates/templates
eof
chmod 0755 $runscript
