#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# dib-lint: disable=safe_sudo

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Disable gpg signing for apt openstack ci repos are created by reprepro
# and not signed.

# This has to be after debootstrap, but before anything else tries to
# use the mirror.

APT_DIR=${TARGET_ROOT}/etc/apt/apt.conf.d

if [ -d ${APT_DIR} ]; then
    FILE=${APT_DIR}/99unauthenticated
    sudo dd of=${FILE} <<EOF
APT::Get::AllowUnauthenticated "true";
EOF
    sudo chmod 0644 ${FILE}
fi
