#!/bin/bash
# Copyright 2012 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# options for create-baremetal-image.sh
if [ -f /etc/debian_version ]; then
  _ARCH=$(dpkg --print-architecture)
else
  _ARCH=$(uname -m)
  case $_ARCH in
    "x86_64")
      _ARCH="amd64"
      ;;
    "armv"*)
      _ARCH="armhf"
      ;;
    *)
      echo "WARNING: Unknown architecture: $_ARCH"
      ;;
  esac
fi
ARCH=${ARCH:-$_ARCH}
export ARCH

export DIB_NO_TMPFS=${DIB_NO_TMPFS:-0}
export DIB_MIN_TMPFS=${DIB_MIN_TMPFS:-2}
# Set via the CLI normally.
# IMAGE_ELEMENT=
_BASE_ELEMENT_DIR=$_PREFIX/elements
ELEMENTS_PATH=${ELEMENTS_PATH:+"$ELEMENTS_PATH:$_BASE_ELEMENT_DIR"}
export ELEMENTS_PATH=${ELEMENTS_PATH:-$_BASE_ELEMENT_DIR}
export DIB_OFFLINE=${DIB_OFFLINE:-''}

# /sbin and friends aren't automatically included in $PATH when running sudo
# on Fedora/RHEL/SUSE Linux which breaks various pieces of this script in
# exciting ways, so inject them into the current $PATH if they're not there.
if ! [[ ":$PATH" =~ ":/sbin" ]] ; then
  export PATH=$PATH:/sbin
fi
if ! [[ ":$PATH" =~ ":/usr/sbin" ]] ; then
  export PATH=$PATH:/usr/sbin
fi
if ! [[ ":$PATH" =~ ":/usr/local/sbin" ]] ; then
  export PATH=$PATH:/usr/local/sbin
fi
