#!/bin/sh

# Install controller base requiered packages

set -e
set -o xtrace

#install-packages sysstat mytop percona-toolkit percona-server-server-5.5 percona-server-client-5.5
install-packages sysstat mytop percona-toolkit mysql-server-5.5 mysql-client-5.5
