#!/bin/bash
set -e

if [ -d /etc/first-boot.d ]; then
    rc_local=/etc/rc.d/rc.local

    FILE_EXISTED=
    if [ -f $rc_local ]
    then
        FILE_EXISTED=1
        mv $rc_local $rc_local.REAL
    fi

    dd of=$rc_local <<EOF
#!/bin/bash
set -e
set -o xtrace

dib-first-boot
EOF

    if [ $FILE_EXISTED ]
    then
        echo "mv $rc_local.REAL $rc_local" >> $rc_local
    else
        echo "rm \$0" >> $rc_local
    fi

    echo "exit 0" >> $rc_local

    chmod 755 $rc_local

    # Enable the service
    systemctl enable rc-local.service
fi
