#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# without these files, cloud-init will not perform stock operations such as
# generating sshd hostkeys.

mkdir -p /var/lib/cloud/seed/nocloud
touch /var/lib/cloud/seed/nocloud/user-data
touch /var/lib/cloud/seed/nocloud/meta-data
