#!/bin/bash
# Do an apt-get clean. This will free some space.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "${DIB_DISABLE_APT_CLEANUP:-0}" != "1" ]; then
    apt-get clean
fi
