#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

for f in $(find $(dirname $0)/../bin/ -type f -executable -print); do
    install -m 0755 -o root -g root $f /usr/local/bin
done
