#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# exit directly if DIB_YUM_REPO_CONF is not defined properly
if [ -z "${DIB_YUM_REPO_CONF:-}" ] ; then
    echo "DIB_YUM_REPO_CONF is not set - no repo configurations will be cleaned up"
    exit 0
fi

for file in $DIB_YUM_REPO_CONF; do
    sudo rm -f $TMP_MOUNT_PATH/etc/yum.repos.d/$(basename $file)
done
