#!/bin/bash
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# hack to get python into Xenial python3 only images, while we
# work-around issues.
apt-get -y install python || true
