#!/bin/bash
# The grub post-kernel install hook will barf if the block device can't be
# found (as happens in a chroot).
# Temporarily remove grub, to avoid that confusion.

set -e

if dpkg-query -W grub-pc; then
  apt-get -y remove grub-pc
fi

if dpkg-query -W grub2-common; then
  apt-get -y remove grub2-common
fi
