#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        # nothing to do
        exit 0
        ;;
    systemd)
        if [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
            systemctl enable ssh.service
        else
            systemctl enable sshd.service
        fi
        ;;
    openrc)
        # let dib-init-system's postinstall handle enabling init scripts
        exit 0
        ;;
    sysv)
        # ssh is enabled by default, nothing to do
        exit 0
        ;;
    *)
        echo "Unsupported init system $DIB_INIT_SYSTEM"
        exit 1
        ;;
esac
