#!/bin/bash

# Recreate the initramfs within the loop device so everything gets
# picked up correctly.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

dracut --regenerate-all --force --verbose
