#!/bin/bash
#
# Copyright 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -f /etc/locale.gen ] && rm /etc/locale.gen

debconf-set-selections - <<EOF
locales locales/locales_to_be_generated multiselect en_US.UTF-8 UTF-8
# Choices: None, C.UTF-8, en_US.UTF-8
locales locales/default_environment_locale select en_US.UTF-8
EOF

dpkg-reconfigure -f noninteractive locales

# set on configuration
cat > /etc/default/locale <<EOF
LANG=$DIB_DEBOOTSTRAP_DEFAULT_LOCALE
LC_ALL=$DIB_DEBOOTSTRAP_DEFAULT_LOCALE
EOF
