#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

package-uninstalls -d $(dirname $0)
package-installs-v2 --phase pre-install.d --uninstall /tmp/package-installs.json
