#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ 'ubuntu' != $DISTRO_NAME ]; then
    echo "Only ubuntu is supported for LVM support. The DISTRO is set to $DISTRO_NAME"
    exit 1
fi

if [[ ! $DIB_RELEASE =~ (xenial|bionic) ]]; then
    echo "Only xenial and bionic are supported for LVM support. The DIB_RELEASE is set to $DIB_RELEASE"
    exit 1
fi
