#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -x "$TMP_MOUNT_PATH/tmp/clean_up_qemu_binary" ] ; then
    "$TMP_MOUNT_PATH/tmp/clean_up_qemu_binary"
    rm -rf "$TMP_MOUNT_PATH/tmp/clean_up_qemu_binary"
fi
