#!/bin/bash
# Ensure we load the mellanox driver somehow

set -e

home=$(dirname $0)

install -m 0644 -o root -g root $home/mellanox-rules.udev /etc/udev/rules.d/81-mellanox.rules
echo "mlx4_en" >>/etc/modules
