#!/bin/bash

set -eu
set -o pipefail

cat << EOF > /etc/yum.repos.d/epel.repo
[epel]
name=epel
failovermethod=priority
baseurl=http://download-i2.fedoraproject.org/pub/epel/beta/7/x86_64/
enabled=1
metadata_expire=7d
gpgcheck=0
EOF

cat << EOF > /etc/yum.repos.d/bnemec-os-config.repo
[bnemec-os-config]
name=Copr repo for os-config owned by bnemec
baseurl=http://copr-be.cloud.fedoraproject.org/results/bnemec/os-config/epel-7-x86_64/
skip_if_unavailable=True
gpgcheck=0
enabled=1
EOF
