#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DISTRO_NAME =~ "centos" ]]; then
    eval declare -A image_elements=($(get_image_element_array))
    if [[ ! "${image_elements[@]}" =~ "dracut-regenerate" ]]; then
        echo "The dracut-regenerate element is required!"
        exit 1
    fi
fi
