#!/bin/bash

home=$(dirname $0)
set -uex

install-packages python-pip

cd /opt/stack/config-applier
pip install -e . -U

install -m 0644 -o root -g root $home/config-applier.upstart /etc/init/config-applier.conf
