#!/bin/bash
# Save user SSH public key if available.
# (Obviously not suitable for downloadable images).

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

source $_LIB/die
[ -n "$TMP_HOOKS_PATH" ] || die "Temp hook path not set"

if [ -e ~/.ssh/authorized_keys ]; then
    cat ~/.ssh/authorized_keys > $TMP_HOOKS_PATH/ssh-authorized-keys
fi
