#!/bin/bash
#
# Copyright 2014 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -f ${TARGET_ROOT}/.extra_settings ] ; then
    . ${TARGET_ROOT}/.extra_settings
fi

[ -n "$DISTRO_NAME" ]
[ -n "$DIB_RELEASE" ]
[ -n "$DIB_DISTRIBUTION_MIRROR" ]

if [ $DISTRO_NAME = 'ubuntu' ] ; then
    KERNEL='generic'
else
    case $ARCH in
        amd64) KERNEL='amd64' ;;
        i386) KERNEL='686' ;;
        arm7)
            [ -n "$DIB_ARM_KERNEL" ]
            KERNEL="$DIB_ARM_KERNEL"
            ;;
    esac
fi
KERNEL_PACKAGE="linux-image-$KERNEL"

DIB_DEBIAN_COMPONENTS=${DIB_DEBIAN_COMPONENTS:-main}
DIB_DEBOOTSTRAP_EXTRA_ARGS=${DIB_DEBOOTSTRAP_EXTRA_ARGS:-}
DEBOOTSTRAP_TARBALL=$DIB_IMAGE_CACHE/debootstrap-${DISTRO_NAME}-${DIB_RELEASE}-${ARCH}-${KERNEL}.tar.gz
http_proxy=${http_proxy:-}

if [ -n "$DIB_OFFLINE" -o -n "${DIB_DEBIAN_USE_DEBOOTSTRAP_CACHE:-}" ] && [ -f $DEBOOTSTRAP_TARBALL ] ; then
    echo $DEBOOTSTRAP_TARBALL found in cache. Using.
    sudo tar -C $TARGET_ROOT --numeric-owner -xzf $DEBOOTSTRAP_TARBALL
else

    KEYRING_OPT=
    if [ -n "${DIB_APT_KEYRING:-${DIB_DEBIAN_KEYRING:-}}" ] ; then
        KEYRING_OPT="--keyring=${DIB_APT_KEYRING:-${DIB_DEBIAN_KEYRING:-}}"
    fi

    # Have to --include=python because of dib-run-parts
    # Have to --include=sudo for pre-install.d use of sudoers files
    sudo sh -c "http_proxy=$http_proxy debootstrap --verbose \
        --variant=minbase \
        --include=python,sudo,$KERNEL_PACKAGE \
        --components=${DIB_DEBIAN_COMPONENTS} \
        --arch=${ARCH} \
        $KEYRING_OPT \
        $DIB_DEBOOTSTRAP_EXTRA_ARGS \
        $DIB_RELEASE \
        $TARGET_ROOT \
        $DIB_DISTRIBUTION_MIRROR \
        ${DIB_DEBIAN_DEBOOTSTRAP_SCRIPT:-}"

    echo Caching debootstrap result in $DEBOOTSTRAP_TARBALL
    if [ "${DIB_DEBOOTSTRAP_CACHE:-0}" != "0" ]; then
        sudo tar --numeric-owner -C $TARGET_ROOT -zcf $DEBOOTSTRAP_TARBALL --exclude='./tmp/*' .
    fi
fi

sudo rm -f ${TARGET_ROOT}/.extra_settings
