#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TARGET_ROOT" ]

# Prevent package installs from starting daemons
sudo mv $TARGET_ROOT/sbin/start-stop-daemon $TARGET_ROOT/sbin/start-stop-daemon.REAL
sudo dd of=$TARGET_ROOT/sbin/start-stop-daemon <<EOF
#!/bin/sh
echo
echo "Warning: Fake start-stop-daemon called, doing nothing"
EOF
sudo chmod 755 $TARGET_ROOT/sbin/start-stop-daemon

if [ -f $TARGET_ROOT/sbin/initctl ]; then
    sudo mv $TARGET_ROOT/sbin/initctl $TARGET_ROOT/sbin/initctl.REAL
    sudo dd of=$TARGET_ROOT/sbin/initctl <<EOF
#!/bin/sh
echo "initctl (tripleo 1.0)"
echo "Warning: Fake initctl called, doing nothing"
EOF
    sudo chmod 755 $TARGET_ROOT/sbin/initctl
fi

sudo dd of=$TARGET_ROOT/usr/sbin/policy-rc.d <<EOF
#!/bin/sh
# 101 Action not allowed. The requested action will not be performed because
#     of runlevel or local policy constraints.
exit 101
EOF
sudo chmod 755 $TARGET_ROOT/usr/sbin/policy-rc.d
