#!/bin/bash
#
# Copyright 2014 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TARGET_ROOT" ]

source $_LIB/img-functions

if [ -d $TARGET_ROOT/boot/extlinux ] ; then
    CONF=$TARGET_ROOT/boot/extlinux/extlinux.conf
elif [ -d $TARGET_ROOT/boot/syslinux ] ; then
    CONF=$TARGET_ROOT/boot/syslinux/syslinux.cfg
else
    exit 0
fi

# Dig up the initrd and kernel to use.
select_boot_kernel_initrd $TARGET_ROOT

sudo sh -c "cat > $CONF <<_EOF_
DEFAULT linux

LABEL linux
    KERNEL /boot/$KERNEL
    APPEND ro root=LABEL=${DIB_ROOT_LABEL} console=tty0 console=ttyS0,115200 nofb nomodeset vga=normal
    INITRD /boot/$RAMDISK
_EOF_"
