#!/bin/bash
# Fully upgrade everything on the system (if the package manager knows how to
# do it).

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

install-packages -u
