#!/bin/bash
# Store build-time environment and command line arguments

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -e "/tmp/in_target.d/dib_environment" ]; then
    cp /tmp/in_target.d/dib_environment /etc/
fi

if [ -e "/tmp/in_target.d/dib_arguments" ]; then
    cp /tmp/in_target.d/dib_arguments /etc/
fi
