#!/bin/bash

set -e
set -o xtrace

source $(dirname $0)/defaults

if [ "$HTTP_PROXY" != "true" ]; then
    exit 0
fi

# ToDo: Only nginx available for now
apt-get install -y nginx

cp $(dirname $0)/httpproxy.jenkins /etc/nginx/sites-available/
sed -i 's/server_name ci.yourcompany.com;/server_name ${SERVER_NAME};/' /etc/nginx/sites-available/httpproxy.jenkins
ln -s /etc/nginx/sites-available/httpproxy.jenkins /etc/nginx/sites-enabled/
rm /etc/nginx/sites-enabled/default
