#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

FILE=/usr/local/bin/dib-init-system

# This is a dummy script that simply echos the output of
# ${DIB_INIT_SYSTEM}.  This script used to try and guess the init
# system, but that doesn't work.  This script is deprecated.

cat > ${FILE} <<EOF
#!/bin/bash
echo ${DIB_INIT_SYSTEM}
EOF

chown root:root ${FILE}
chmod 775 ${FILE}
