#!/bin/bash

set -e

[ -n "$TARGET_ROOT" ]

DISTRO=`lsb_release -si` || true

if [[ "Fedora RedHatEnterpriseServer" =~ "$DISTRO" ]]; then
  mkdir -p "$TARGET_ROOT/usr"
  ln -s ../lib "$TARGET_ROOT/usr/lib"
  if [ "`uname -m`" = "x86_64" ]; then
      ln -s lib "$TARGET_ROOT/lib64"
  fi
fi
