#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


[ -n "$TARGET_ROOT" ]

source $_LIB/img-functions

IMAGE_PATH=$(readlink -f $IMAGE_NAME)
cd $TARGET_ROOT

echo "#disabled" > ./tmp/fstab.new
sudo mv ./tmp/fstab.new ./etc/fstab
sudo ln -s ./sbin/init ./

# Remove python object files, they're not particularly useful for a ramdisk
sudo find ./usr -name "*.pyc" -or -name "*.pyo" -delete

# Note: The pci.ids, which is used by lshw, locate on Ubuntu
# in /usr/share/misc. Therefore we are removing only the
# ./usr/share/misc/m* (will remove the magic and magic.mgc files).
# on RHEL pci.ids is locate on /usr/share/hwdata/pci.ids.
sudo find . -xdev \
    -path './sys/*' -prune -o \
    -path './tmp/*' -prune -o \
    -path './boot/*' -prune -o \
    -path './root/.cache' -prune -o \
    -path './usr/lib/locale/*' -prune -o \
    -path './usr/share/doc/*' -prune -o \
    -path './usr/share/man/*' -prune -o \
    -path './usr/share/info/*' -prune -o \
    -path './usr/share/licenses/*' -prune -o \
    -path './usr/share/misc/m*' -prune -o \
    -print | sudo cpio -o -H newc | gzip > ${IMAGE_PATH}.initramfs

select_boot_kernel_initrd $TARGET_ROOT
sudo cp $BOOTDIR/$KERNEL ${IMAGE_PATH}.kernel

# TODO(lucasagomes): Create a hard link for the .vmlinuz file to keep
# it backward compatible. Remove it after it has been consistent and
# documented in both places for at least one full OpenStack release cycle
echo "WARNING: The kernel extension .vmlinuz has been deprecated. Please rely on the file with the extension .kernel instead."
sudo rm -f ${IMAGE_PATH}.vmlinuz
sudo ln ${IMAGE_PATH}.kernel ${IMAGE_PATH}.vmlinuz
