#!/bin/bash
# Copyright (c) 2024 ECMWF
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    systemd)
        if [[ $DISTRO_NAME =~ (ubuntu|debian)$ ]]; then
            systemctl enable unattended-upgrades.service
        elif [[ $DISTRO_NAME =~ (centos|rocky|rhel|openeuler)$ ]]; then
            systemctl enable dnf-automatic.timer
        else
            echo "The 'autoupdates' element does not support this distribution."
            echo "Exiting"
            exit 1
        fi
esac
