#!/bin/bash
# These are useful, or at worst not harmful, for all images we build.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ ${DIB_SKIP_BASE_PACKAGE_INSTALL} -eq 0 ]; then
    install-packages -m base iscsi_package
fi
