#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

exec sudo install -m 0755 -o root -g root -D \
    $(which dib-run-parts) \
    $TARGET_ROOT/usr/local/bin/dib-run-parts
