#!/bin/bash
set -eux

modprobe nbd || true

chown -R nova:nova /var/log/nova

# TODO: for compute nodes only
mkdir -p /var/run/nova/instances
chown -R nova:nova /var/run/nova
mkdir -p /tftpboot
chown -R nova:nova /tftpboot
service nova-conductor restart
service nova-api restart
service nova-cert restart
service nova-rpc-zmq-receiver restart
service nova-compute restart
service nova-scheduler restart
service nova-consoleauth restart
service nova-baremetal-deploy-helper restart
service nova-bm-dnsmasq restart
