- project:
    templates:
      - openstack-cover-jobs
      - check-requirements
      - openstack-lower-constraints-jobs
      - release-notes-jobs
      # NOTE(ianw): 2020-05-29 jobs are unstable; see
      # https://bugs.launchpad.net/tripleo/+bug/1879766
      - tripleo-buildimage-jobs-centos-8
      - openstack-python35-jobs
      - openstack-python3-victoria-jobs
    check:
      jobs:
        - openstack-tox-pylint
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-centos-8-src
        - dib-nodepool-functional-openstack-centos-8-stream-src
        - dib-nodepool-functional-openstack-fedora-31-src
        - dib-nodepool-functional-openstack-fedora-32-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-ubuntu-focal-src
        # NOTE(ianw): 2020-04-22 these have been out of the gate for a
        # while; promote to voting after some stability.
        - dib-nodepool-functional-openstack-opensuse-15-src:
            voting: false
        - dib-nodepool-functional-openstack-opensuse-tumbleweed-src:
            voting: false
        - dib-functests-bionic-python3
        - dib-functests-bionic-python3-image
        - dib-functests-bionic-python3-extras
        - dib-functests-bionic-python3-containers
        - ironic-python-agent-check-image-dib-centos8
        # IPA jobs that build AND validate an image via deployment (two ways).
        - ipa-tempest-wholedisk-bios-ipmi-direct-dib-src:
            voting: false
        - ipa-tempest-bios-ipmi-iscsi-src:
            voting: false
    check-arm64:
      jobs:
        - dib-functests-arm64-bionic
    gate:
      jobs:
        - openstack-tox-pylint
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-centos-8-src
        - dib-nodepool-functional-openstack-centos-8-stream-src
        - dib-nodepool-functional-openstack-fedora-31-src
        - dib-nodepool-functional-openstack-fedora-32-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-ubuntu-focal-src
        - dib-functests-bionic-python3
        - ironic-python-agent-check-image-dib-centos8
    experimental:
      jobs:
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-gentoo-src
        - dib-nodepool-functional-openstack-debian-stretch-src
        - dib-nodepool-functional-openstack-debian-buster-src
        - octavia-v1-dsvm-scenario
        - octavia-v1-dsvm-py3x-scenario
