#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# zeroconf should not be activated or it will add a 169.254.0.0
# route. The route will interfere with access to the nova metadata
# server at 169.254.169.254.
if ! grep NOZEROCONF /etc/sysconfig/network ; then
    echo "NOZEROCONF=yes" >> /etc/sysconfig/network
fi
