#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    upstart)
        # nothing to do
        exit 0
        ;;
    systemd)
        systemctl enable growroot.service
        ;;
    openrc)
        # let dib-init-system's postinstall handle enabling init scripts
        exit 0
        ;;
    *)
        echo "Unsupported init system"
        exit 1
        ;;
esac
