#!/usr/bin/python

# Copyright 2014 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import rtslib

import targetcli_bin


class MyISCSIFabricModule(rtslib.fabric.ISCSIFabricModule):
    def __init__(self):
        super(rtslib.fabric.ISCSIFabricModule, self).__init__('iscsi')
        self.wwn_types = ('free',)


rtslib.fabric.fabric_modules['iscsi'] = MyISCSIFabricModule


targetcli_bin.main()
