#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
    systemd)
        systemctl enable dynamic-login.service
        ;;
    sysv)
        update-rc.d dynamic-login.init defaults
        ;;
esac
