#!/bin/bash
set -eu
set -o pipefail

if [ -d /etc/first-boot.d ]; then
    rc_local=/etc/rc.local

    mv $rc_local $rc_local.REAL

    dd of=$rc_local <<EOF
#!/bin/bash
set -e
set -o xtrace

dib-first-boot

mv $rc_local.REAL $rc_local
exit 0
EOF

chmod 755 $rc_local
fi
