#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ "i386" = "$ARCH" ]; then
    basearch=i386
    arch=i686
elif [[ "amd64 x86_64" =~ "$ARCH" ]]; then
    basearch=x86_64
    arch=x86_64
elif [[ "$ARCH" = "ppc64" ]]; then
    basearch=ppc64
    arch=ppc64
elif [[ "$ARCH" = "ppc64le" ]]; then
    basearch=ppc64le
    arch=ppc64le
elif [[ "arm64 aarch64" =~ "$ARCH" ]]; then
    basearch=aarch64
    arch=aarch64
else
    echo "********************"
    echo "Unknown arch '$ARCH'"
    echo "********************"
    exit 1
fi

if [[ $DISTRO_NAME == "fedora" && $DIB_RELEASE -ge 22 ]]; then
    mkdir -p /etc/dnf/vars
    echo $basearch > /etc/dnf/vars/basearch
    echo $arch > /etc/dnf/vars/arch
else
    echo $basearch > /etc/yum/vars/basearch
    echo $arch > /etc/yum/vars/arch
fi
