#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi

set -eu
set -o pipefail

if [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
    echo "ISCSI_AUTO=true" > /etc/iscsi/iscsi.initramfs
    update-initramfs -u
fi
