#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          ironic-python-agent
# Required-Start:    $local_fs networking
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# X-Start-Before:
# Short-Description: Ironic Python Agent
# Description:       Starts Ironic Python Agent for instance deployment
### END INIT INFO

NAME=ironic-python-agent
INIT_NAME=/etc/init.d/${NAME}
SCRIPT_NAME=/usr/local/bin/${NAME}

[ -x $SCRIPT_NAME ] || exit 0

case "$1" in
    start)
        $SCRIPT_NAME
        ;;
    stop)
        ;;
    *)
        echo "Usage: $INIT_NAME {start|stop}"
        exit 1
        ;;
esac

exit 0
