#!/bin/bash

set -eu
set -o pipefail

RET=$(/bin/select-boot-kernel-initrd)
KERNEL_VERSION=`echo ${RET%:*} | sed 's/vmlinuz-//g'`
RAMDISK=/boot/${RET#*:}

dracut --force --add "network" $RAMDISK $KERNEL_VERSION
