#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

MODULES_LIST=${DIB_MODPROBE_BLACKLIST:?"Please set DIB_MODPROBE_BLACKLIST."}

for mod_name in $MODULES_LIST; do
    echo "blacklist $mod_name" >> /etc/modprobe.d/blacklist.conf
done
