#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

sudo rm -f $TMP_MOUNT_PATH/lib/diskimage-builder/img-functions
sudo rmdir $TMP_MOUNT_PATH/lib/diskimage-builder
