#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TARGET_ROOT" ]

sudo rm $TARGET_ROOT/etc/dpkg/dpkg.cfg.d/02apt-speedup
sudo rm $TARGET_ROOT/etc/apt/apt.conf.d/no-languages
