#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ ${GENTOO_OVERLAYS} != '' ]]; then
    if mountpoint -q /dev/shm; then
    echo "/dev/shm found in /proc/self/mountinfo"
    elif [[ -k /dev/shm ]]; then
        echo "/dev/shm exists and is stickied"
    else
        fix_shm
    fi

    if [[ ! -f ${PORTDIR}/profiles ]]; then
        emerge-webrsync -q
    fi

    emerge ${GENTOO_EMERGE_DEFAULT_OPTS} --oneshot openssl openssh
    # install layman
    emerge ${GENTOO_EMERGE_DEFAULT_OPTS} --deep --ignore-built-slot-operator-deps=y layman
    # set layman config options
    sed -i 's/^check_official.*/check_official : No/g' /etc/layman/layman.cfg # allow unoffical repos
    # sync the initial overlay list
    layman -S
    # enable the various overlays, ignore failures (overlay my already be enabled)
    set +e
    for OVERLAY in ${GENTOO_OVERLAYS}; do
        layman -a "${OVERLAY}"
    done
    set -e

    unfix_shm
fi
